version: "3.6"

services:
  default:
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - ".env"
    volumes:
      - "./pacman-cache:/srv/http/pacman-cache"
      - type: tmpfs
        target: /pacman-cache
    restart: always
